from typing import Any


CHECKED_AT = "2026-06-12"


def representative_products() -> list[dict[str, Any]]:
    return [
        _product(
            id="samsung-refrigerator-family",
            name="삼성 냉장고",
            category="냉장고",
            method="삼성 가정용 냉장고 대표 제품군",
            summary="선반, 서랍, 문 고무패킹과 내부 물기를 중심으로 관리해요.",
            frequency="내부 오염은 발견 즉시 · 전체 내부는 한 달마다",
            days=30,
            minutes=20,
            official_title="삼성전자 냉장고 공식 제품군",
            official_url="https://www.samsung.com/sec/refrigerators/all-refrigerators/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "유리 선반은 실온에 둔 뒤 닦아 급격한 온도 변화를 피하세요.",
                "내부에 세제를 직접 분사하지 마세요.",
            ],
            steps=[
                "상하기 쉬운 식품을 보냉 가방에 옮겨요.",
                "분리 가능한 선반과 서랍을 제품 설명서에 따라 꺼내요.",
                "중성세제를 묻힌 부드러운 천으로 내부와 문 고무패킹을 닦아요.",
                "물기를 완전히 제거한 뒤 부품과 식품을 다시 넣어요.",
            ],
            keywords=["냉장고", "비스포크", "refrigerator", "삼성"],
        ),
        _product(
            id="samsung-wf25cb8895bw",
            name="삼성 Bespoke AI 세탁기",
            category="세탁기",
            model="WF25CB8895BW",
            method="드럼 세탁기 · 무세제통세척+ 지원",
            summary="세제함, 도어 패킹과 배수 필터를 관리하고 통세척 기능을 활용해요.",
            frequency="세제함과 패킹은 오염 시 · 배수 필터는 한 달마다",
            days=30,
            minutes=20,
            official_title="Bespoke AI 세탁기 25kg 공식 지원",
            official_url="https://www.samsung.com/sec/support/model/WF25CB8895BW/",
            supplies=["부드러운 천", "작은 솔", "고무장갑"],
            cautions=[
                "필터를 열기 전에 전원을 끄고 잔수가 나올 수 있도록 수건을 준비하세요.",
                "세탁조 전용 기능과 세정제 사용 여부는 설명서를 우선 확인하세요.",
            ],
            steps=[
                "세제함을 분리해 남은 세제와 섬유유연제를 씻어내요.",
                "도어 고무패킹의 이물질과 물기를 닦아요.",
                "배수 필터는 설명서의 분리 순서와 잔수 배출 방법을 따라 관리해요.",
                "빈 통 상태에서 제품의 무세제통세척+ 코스를 실행해요.",
            ],
            keywords=["세탁기", "드럼", "WF25CB8895BW", "삼성"],
            specs=[
                "모델명: WF25CB8895BW",
                "세탁 용량: 25kg",
                "관리 기능: 무세제통세척+",
                "출시년월: 2023년 3월",
            ],
            release_year=2023,
        ),
        _product(
            id="samsung-kq65qnf70afxkr",
            name="삼성 Neo QLED QNF70 TV",
            category="TV",
            model="KQ65QNF70AFXKR",
            method="2025 Neo QLED 4K 163cm",
            summary="화면에는 액체를 직접 뿌리지 않고 마른 극세사 천으로 가볍게 관리해요.",
            frequency="화면 먼지는 필요할 때 · 통풍구는 한 달마다",
            days=30,
            minutes=10,
            official_title="2025 Neo QLED QNF70 공식 지원",
            official_url="https://www.samsung.com/sec/support/model/KQ65QNF70AFXKR/",
            supplies=["마른 극세사 천", "부드러운 먼지 브러시"],
            cautions=[
                "화면에 물이나 세정제를 직접 분사하지 마세요.",
                "화면을 강하게 누르거나 거친 천으로 문지르지 마세요.",
            ],
            steps=[
                "TV 전원을 끄고 화면의 열이 식을 때까지 기다려요.",
                "마른 극세사 천으로 화면 먼지를 힘주지 않고 닦아요.",
                "후면 통풍구와 스탠드의 먼지를 부드러운 브러시로 제거해요.",
                "케이블이 눌리거나 통풍구를 가리지 않는지 확인해요.",
            ],
            keywords=["TV", "텔레비전", "QNF70", "KQ65QNF70AFXKR", "삼성"],
            specs=[
                "모델명: KQ65QNF70AFXKR",
                "화면 크기: 163cm",
                "해상도: 4K",
                "제품군: 2025 Neo QLED QNF70",
            ],
            release_year=2025,
        ),
        _product(
            id="samsung-air-conditioner-family",
            name="삼성 스탠드 에어컨",
            category="에어컨",
            method="삼성 가정용 스탠드 에어컨 대표 제품군",
            summary="흡입 필터의 먼지를 제거하고 완전히 건조한 뒤 다시 장착해요.",
            frequency="흡입 필터는 2주마다 · 사용 전후 상태 확인",
            days=14,
            minutes=20,
            official_title="삼성전자 에어컨 공식 제품군",
            official_url="https://www.samsung.com/sec/air-conditioners/all-air-conditioners/",
            supplies=["청소기 브러시", "부드러운 천", "고무장갑"],
            cautions=[
                "전원을 끄고 플러그 또는 차단기를 확인한 뒤 필터를 분리하세요.",
                "열교환기나 전기 부품에 물을 직접 뿌리지 마세요.",
            ],
            steps=[
                "전원을 끄고 제품이 완전히 멈춘 것을 확인해요.",
                "설명서에 따라 흡입 필터를 분리해 먼지를 제거해요.",
                "물세척 가능한 필터만 세척하고 그늘에서 완전히 말려요.",
                "냄새, 누수 또는 이상 소음이 있으면 전문 서비스를 요청해요.",
            ],
            keywords=["에어컨", "스탠드", "무풍", "air conditioner", "삼성"],
        ),
        _product(
            id="samsung-ms23c3535ak",
            name="삼성 전자레인지",
            category="전자레인지",
            model="MS23C3535AK",
            method="삼성 전자레인지 대표 모델",
            summary="내부 음식물 흔적과 회전판을 닦고 충분히 건조해 냄새를 줄여요.",
            frequency="오염은 사용 후 · 내부 전체는 주 1회",
            days=7,
            minutes=10,
            official_title="MS23C3535AK 공식 지원",
            official_url="https://www.samsung.com/sec/support/model/MS23C3535AK/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "전원 플러그를 분리하고 내부가 식은 뒤 관리하세요.",
                "통풍구와 전기 부품에 물이 들어가지 않게 하세요.",
            ],
            steps=[
                "전원을 분리하고 내부가 식었는지 확인해요.",
                "회전판과 받침을 분리해 중성세제로 닦아요.",
                "내부 벽면과 문 안쪽의 음식물 흔적을 부드러운 천으로 닦아요.",
                "모든 부품을 완전히 말린 뒤 다시 장착해요.",
            ],
            keywords=["전자레인지", "microwave", "MS23C3535AK", "삼성"],
            specs=["모델명: MS23C3535AK", "제품 유형: 전자레인지"],
        ),
        _product(
            id="samsung-vacuum-family",
            name="삼성 무선청소기",
            category="청소기",
            method="삼성 Bespoke Jet 무선청소기 대표 제품군",
            summary="먼지통, 브러시와 세척 가능한 필터를 제품 설명서에 맞게 관리해요.",
            frequency="먼지통은 사용 후 · 브러시와 필터는 한 달마다",
            days=30,
            minutes=15,
            official_title="삼성전자 청소기 공식 제품군",
            official_url="https://www.samsung.com/sec/vacuum-cleaners/all-vacuum-cleaners/",
            supplies=["마른 천", "작은 솔", "가위"],
            cautions=[
                "배터리와 모터부는 물로 세척하지 마세요.",
                "세척한 필터는 완전히 건조한 뒤 장착하세요.",
            ],
            steps=[
                "전원을 끄고 먼지통을 비워요.",
                "브러시에 감긴 머리카락과 실을 제거해요.",
                "설명서에서 물세척 가능하다고 표시된 부품만 세척해요.",
                "부품을 완전히 건조한 뒤 정확히 조립해요.",
            ],
            keywords=["청소기", "무선청소기", "비스포크 제트", "vacuum", "삼성"],
        ),
        _product(
            id="samsung-dryer-family",
            name="삼성 건조기",
            category="건조기",
            method="삼성 Bespoke AI 건조기 대표 제품군",
            summary="보풀 필터는 사용할 때마다 비우고 센서와 열교환기는 설명서에 맞게 관리해요.",
            frequency="보풀 필터는 사용할 때마다 · 센서는 한 달마다",
            days=7,
            minutes=10,
            official_title="삼성전자 세탁기·건조기 공식 제품군",
            official_url="https://www.samsung.com/sec/washers-and-dryers/all-washers-and-dryers/",
            supplies=["부드러운 솔", "마른 천", "청소기 브러시"],
            cautions=[
                "젖은 필터를 장착하거나 열교환기 핀을 강하게 누르지 마세요.",
                "제품 내부를 임의로 분해하지 마세요.",
            ],
            steps=[
                "사용 후 보풀 필터를 꺼내 먼지를 제거해요.",
                "필터를 세척했다면 완전히 건조해 다시 장착해요.",
                "습도 센서를 부드러운 마른 천으로 닦아요.",
                "열교환기 관리는 모델별 설명서의 주기와 방법을 확인해요.",
            ],
            keywords=["건조기", "의류건조기", "dryer", "비스포크", "삼성"],
        ),
        _product(
            id="samsung-air-purifier-family",
            name="삼성 공기청정기",
            category="공기청정기",
            method="삼성 Bespoke 큐브 공기청정기 대표 제품군",
            summary="흡입구와 프리필터의 먼지를 제거하고 교체 필터 상태를 확인해요.",
            frequency="외부와 프리필터는 한 달마다",
            days=30,
            minutes=15,
            official_title="삼성전자 공기청정기 공식 제품군",
            official_url="https://www.samsung.com/sec/air-cleaner/all-air-cleaner/",
            supplies=["청소기 브러시", "마른 천"],
            cautions=[
                "집진·탈취 필터의 물세척 가능 여부를 설명서에서 확인하세요.",
                "전원을 분리한 뒤 필터 커버를 여세요.",
            ],
            steps=[
                "전원을 끄고 플러그를 분리해요.",
                "외부 흡입구의 먼지를 청소기 브러시로 제거해요.",
                "프리필터를 분리해 먼지를 털거나 허용된 경우 세척해요.",
                "필터를 완전히 건조하고 교체 필터의 상태를 확인해요.",
            ],
            keywords=["공기청정기", "공청기", "큐브", "air purifier", "삼성"],
        ),
        _product(
            id="samsung-dishwasher-family",
            name="삼성 식기세척기",
            category="식기세척기",
            method="삼성 Bespoke 식기세척기 대표 제품군",
            summary="필터, 배수구 주변과 분사 노즐의 음식물 찌꺼기를 관리해요.",
            frequency="필터는 주 1회 확인 · 내부 전체는 한 달마다",
            days=7,
            minutes=15,
            official_title="삼성전자 식기세척기 공식 제품군",
            official_url="https://www.samsung.com/sec/dishwashers/all-dishwashers/",
            supplies=["부드러운 솔", "마른 천", "고무장갑"],
            cautions=[
                "필터와 분사 노즐을 분리하기 전에 전원을 끄세요.",
                "배수 펌프와 내부 배관은 임의로 분해하지 마세요.",
            ],
            steps=[
                "전원을 끄고 내부가 식은 것을 확인해요.",
                "하단 필터를 설명서 순서에 따라 분리해 음식물 찌꺼기를 제거해요.",
                "분사 노즐 구멍과 문 패킹의 오염을 부드러운 솔로 닦아요.",
                "부품을 정확히 조립하고 빈 상태에서 허용된 관리 코스를 실행해요.",
            ],
            keywords=["식기세척기", "dishwasher", "비스포크", "삼성"],
        ),
        _product(
            id="samsung-kimchi-refrigerator-family",
            name="삼성 김치냉장고",
            category="김치냉장고",
            method="삼성 Bespoke 김치플러스 대표 제품군",
            summary="김치통, 선반과 문 고무패킹의 음식물 흔적과 물기를 관리해요.",
            frequency="오염은 발견 즉시 · 내부 전체는 한 달마다",
            days=30,
            minutes=20,
            official_title="삼성전자 김치냉장고 공식 제품군",
            official_url="https://www.samsung.com/sec/kimchi-refrigerators/all-kimchi-refrigerators/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "김치통과 선반의 세척 가능 온도와 방법을 설명서에서 확인하세요.",
                "성에를 날카로운 도구나 열로 제거하지 마세요.",
            ],
            steps=[
                "보관 식품을 다른 냉장 공간으로 옮겨요.",
                "김치통과 분리 가능한 선반을 중성세제로 닦아요.",
                "내부 벽면과 문 고무패킹의 국물 흔적을 부드러운 천으로 닦아요.",
                "물기를 완전히 제거하고 설정 온도를 확인한 뒤 식품을 넣어요.",
            ],
            keywords=["김치냉장고", "김치플러스", "kimchi refrigerator", "삼성"],
        ),
    ]


def _product(
    *,
    id: str,
    name: str,
    category: str,
    method: str,
    summary: str,
    frequency: str,
    days: int,
    minutes: int,
    official_title: str,
    official_url: str,
    supplies: list[str],
    cautions: list[str],
    steps: list[str],
    keywords: list[str],
    model: str = "",
    specs: list[str] | None = None,
    release_year: int | None = None,
) -> dict[str, Any]:
    official_id = f"{id}-official"
    guide_id = f"{id}-editorial-guide"
    product_specs = specs or [
        "삼성전자 대표 제품군 · 정확한 모델명은 제품 라벨에서 확인"
    ]
    spec_source_ids = {
        spec.split(":", maxsplit=1)[0]: [official_id]
        for spec in product_specs
        if ":" in spec
    }
    return {
        "id": id,
        "name": name,
        "type": "appliance",
        "categoryName": category,
        "brand": "삼성전자",
        "manufacturer": "삼성전자",
        "modelName": model,
        "summary": summary,
        "frequency": frequency,
        "recurrenceDays": days,
        "estimatedMinutes": minutes,
        "productMethod": method,
        "guideStatus": (
            "공식 지원 페이지에서 모델을 확인했어요. 관리 순서는 안전한 제품군 공통 범위로 안내해요."
            if model
            else "삼성 공식 제품군을 확인했어요. 정확한 모델별 분해·세척 방법은 제품 라벨과 설명서를 우선해요."
        ),
        "guideBasis": "공식 페이지는 제품 식별 근거로, 관리 순서는 앱 편집팀의 제품군 가이드로 분리해 표시해요.",
        "guideSourceType": "official" if model else "general",
        "matchLevelLabel": "모델명 일치" if model else "브랜드 제품군 기준",
        "sourceTitle": official_title,
        "sourceUrl": official_url,
        "sourceCheckedAt": CHECKED_AT,
        "sources": [
            {
                "id": official_id,
                "title": official_title,
                "url": official_url,
                "type": "officialSupport" if model else "officialProduct",
                "publisher": "삼성전자",
                "checkedAt": CHECKED_AT,
                "supports": ["모델명", "제품군"] if model else ["브랜드", "제품군"],
                "isOfficial": True,
                "isActive": True,
            },
            {
                "id": guide_id,
                "title": f"{category} 안전 관리 가이드",
                "url": None,
                "type": "generalGuidance",
                "publisher": "앱 편집팀",
                "checkedAt": CHECKED_AT,
                "supports": ["준비물", "안전 주의사항", "외부 관리 순서", "권장 확인 주기"],
                "isOfficial": False,
                "isActive": True,
            },
        ],
        "specSourceIds": spec_source_ids,
        "stepSourceIds": {
            str(index): [guide_id] for index, _ in enumerate(steps)
        },
        "reviewHistory": [
            {
                "status": "reviewed",
                "reviewer": "catalog-editor",
                "reviewedAt": CHECKED_AT,
                "note": "공식 제품 식별 정보와 일반 관리 가이드의 근거 범위를 분리해 검수함.",
            }
        ],
        "productSpecs": product_specs,
        "supplies": supplies,
        "recommendedSupplies": supplies,
        "recommendedProducts": [],
        "cautions": cautions,
        "steps": steps,
        "guideVideoUrl": None,
        "guideVideoTitle": None,
        "guideVideoChannel": None,
        "keywords": keywords,
        "reviewStatus": "reviewed",
        "reviewedBy": "catalog-editor",
        "reviewNote": "대표 제품군 10종 1차 검수. 정확 모델 설명서가 확인되면 모델 단위로 갱신.",
        "officialManualUrl": None,
        "supportUrl": official_url,
        "servicePhone": "1588-3366",
        "releaseYear": release_year,
        "isDiscontinued": False,
        "imageUrl": None,
        "consumables": [],
        "installationType": None,
    }
