from typing import Any


CHECKED_AT = "2026-06-12"


def representative_products() -> list[dict[str, Any]]:
    return [
        _product(
            id="samsung-bespoke-ai-refrigerator-4door",
            name="삼성 Bespoke AI 냉장고 4도어",
            category="냉장고",
            series="Bespoke AI 4도어",
            method="상냉장·하냉동 4도어 냉장고 시리즈",
            summary="선반, 서랍, 문 고무패킹과 내부 물기를 중심으로 관리해요.",
            frequency="내부 오염은 발견 즉시 · 전체 내부는 한 달마다",
            days=30,
            minutes=20,
            official_title="삼성전자 Bespoke AI 4도어 냉장고 공식 제품군",
            official_url="https://www.samsung.com/sec/refrigerators/all-refrigerators/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "유리 선반은 실온에 둔 뒤 닦아 급격한 온도 변화를 피하세요.",
                "내부에 세제를 직접 분사하지 마세요.",
            ],
            steps=[
                "상하기 쉬운 식품을 보냉 가방에 옮겨요.",
                "분리 가능한 선반과 서랍을 제품 설명서에 따라 꺼내요.",
                "중성세제를 묻힌 부드러운 천으로 내부와 문 고무패킹을 닦아요.",
                "물기를 완전히 제거한 뒤 부품과 식품을 다시 넣어요.",
            ],
            keywords=["냉장고", "비스포크", "비스포크 AI", "Bespoke AI", "4도어", "refrigerator", "삼성"],
            specs=[
                "시리즈: Bespoke AI",
                "형태: 4도어 냉장고",
                "정확한 모델명은 제품 내부 라벨에서 확인",
            ],
        ),
        _product(
            id="lg-dios-objet-refrigerator-top-bottom",
            name="LG 디오스 오브제컬렉션 냉장고",
            category="냉장고",
            brand="LG전자",
            series="디오스 오브제컬렉션 상냉장·하냉동",
            method="상냉장·하냉동 냉장고 시리즈",
            summary="선반, 서랍, 도어 패킹과 내부의 음식물 흔적을 안전하게 관리해요.",
            frequency="내부 오염은 발견 즉시 · 전체 내부는 한 달마다",
            days=30,
            minutes=20,
            official_title="LG전자 냉장고 공식 제품군",
            official_url="https://www.lge.co.kr/category/refrigerators",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "유리 선반은 차가운 상태에서 뜨거운 물로 씻지 마세요.",
                "조작부와 냉기 토출구에 물이나 세제를 직접 분사하지 마세요.",
            ],
            steps=[
                "상하기 쉬운 식품을 보냉 가방이나 다른 냉장 공간으로 옮겨요.",
                "분리 가능한 선반과 서랍만 모델 설명서에 따라 꺼내요.",
                "희석한 중성세제를 묻힌 부드러운 천으로 내부와 도어 패킹을 닦아요.",
                "깨끗한 천으로 한 번 더 닦고 물기를 완전히 제거한 뒤 식품을 넣어요.",
            ],
            keywords=["냉장고", "디오스", "오브제컬렉션", "상냉장", "하냉동", "refrigerator", "LG"],
            specs=[
                "시리즈: LG 디오스 오브제컬렉션",
                "형태: 상냉장·하냉동",
                "정확한 모델명은 제품 내부 라벨에서 확인",
            ],
        ),
        _product(
            id="samsung-bespoke-ai-washer",
            name="삼성 Bespoke AI 세탁기",
            category="세탁기",
            series="Bespoke AI 세탁기",
            method="삼성 드럼 세탁기 시리즈",
            summary="세제함, 도어 패킹과 배수 필터를 관리하고 모델의 통세척 코스를 확인해요.",
            frequency="세제함과 패킹은 오염 시 · 배수 필터는 한 달마다",
            days=30,
            minutes=20,
            official_title="삼성전자 Bespoke AI 세탁기 공식 제품군",
            official_url="https://www.samsung.com/sec/washers-and-dryers/all-washers-and-dryers/",
            supplies=["부드러운 천", "작은 솔", "고무장갑"],
            cautions=[
                "필터를 열기 전에 전원을 끄고 잔수가 나올 수 있도록 수건을 준비하세요.",
                "세탁조 전용 기능과 세정제 사용 여부는 설명서를 우선 확인하세요.",
            ],
            steps=[
                "세제함을 분리해 남은 세제와 섬유유연제를 씻어내요.",
                "도어 고무패킹의 이물질과 물기를 닦아요.",
                "배수 필터는 설명서의 분리 순서와 잔수 배출 방법을 따라 관리해요.",
                "빈 통 상태에서 모델 설명서에 표시된 통세척 코스를 실행해요.",
            ],
            keywords=["세탁기", "드럼", "비스포크 AI", "Bespoke AI", "삼성"],
            specs=[
                "시리즈: Bespoke AI 세탁기",
                "제품 유형: 드럼 세탁기",
                "정확한 모델명과 용량은 도어 안쪽 라벨에서 확인",
            ],
        ),
        _product(
            id="lg-tromm-objet-drum-washer",
            name="LG 트롬 오브제컬렉션 세탁기",
            category="세탁기",
            brand="LG전자",
            series="트롬 오브제컬렉션 드럼세탁기",
            method="LG 드럼 세탁기 시리즈",
            summary="세제통, 도어 고무패킹과 배수 필터를 관리하고 통살균 코스를 모델별로 확인해요.",
            frequency="세제통과 패킹은 오염 시 · 배수 필터는 한 달마다 확인",
            days=30,
            minutes=20,
            official_title="LG전자 드럼세탁기 공식 제품군",
            official_url="https://www.lge.co.kr/category/washing-machines?subCateId=CT50000102",
            supplies=["부드러운 천", "작은 솔", "고무장갑", "낮은 받침 용기"],
            cautions=[
                "배수 필터를 열기 전 전원을 끄고 잔수가 나올 수 있도록 용기와 수건을 준비하세요.",
                "염소계 세정제나 임의 세정제 사용은 모델 설명서를 먼저 확인하세요.",
            ],
            steps=[
                "세제통을 모델 설명서에 따라 분리해 남은 세제와 섬유유연제를 씻어내요.",
                "도어 고무패킹 주름 안쪽의 이물질과 물기를 부드러운 천으로 닦아요.",
                "잔수를 먼저 배출한 뒤 배수 필터의 이물질을 제거하고 정확히 잠가요.",
                "빈 통 상태에서 모델에 표시된 통살균 또는 통세척 코스를 실행해요.",
            ],
            keywords=["세탁기", "드럼", "트롬", "오브제컬렉션", "TROMM", "LG"],
            specs=[
                "시리즈: LG 트롬 오브제컬렉션",
                "제품 유형: 드럼 세탁기",
                "정확한 모델명과 용량은 도어 안쪽 라벨에서 확인",
            ],
        ),
        _product(
            id="samsung-kq65qnf70afxkr",
            name="삼성 Neo QLED QNF70 TV",
            category="TV",
            model="KQ65QNF70AFXKR",
            method="2025 Neo QLED 4K 163cm",
            summary="화면에는 액체를 직접 뿌리지 않고 마른 극세사 천으로 가볍게 관리해요.",
            frequency="화면 먼지는 필요할 때 · 통풍구는 한 달마다",
            days=30,
            minutes=10,
            official_title="2025 Neo QLED QNF70 공식 지원",
            official_url="https://www.samsung.com/sec/support/model/KQ65QNF70AFXKR/",
            supplies=["마른 극세사 천", "부드러운 먼지 브러시"],
            cautions=[
                "화면에 물이나 세정제를 직접 분사하지 마세요.",
                "화면을 강하게 누르거나 거친 천으로 문지르지 마세요.",
            ],
            steps=[
                "TV 전원을 끄고 화면의 열이 식을 때까지 기다려요.",
                "마른 극세사 천으로 화면 먼지를 힘주지 않고 닦아요.",
                "후면 통풍구와 스탠드의 먼지를 부드러운 브러시로 제거해요.",
                "케이블이 눌리거나 통풍구를 가리지 않는지 확인해요.",
            ],
            keywords=["TV", "텔레비전", "QNF70", "KQ65QNF70AFXKR", "삼성"],
            specs=[
                "모델명: KQ65QNF70AFXKR",
                "화면 크기: 163cm",
                "해상도: 4K",
                "제품군: 2025 Neo QLED QNF70",
            ],
            release_year=2025,
        ),
        _product(
            id="samsung-bespoke-ai-windfree-classic",
            name="삼성 Bespoke AI 무풍클래식",
            category="에어컨",
            series="Bespoke AI 무풍클래식",
            method="삼성 스탠드형 무풍 에어컨 시리즈",
            summary="흡입 필터의 먼지를 제거하고 완전히 건조한 뒤 다시 장착해요.",
            frequency="흡입 필터는 2주마다 · 사용 전후 상태 확인",
            days=14,
            minutes=20,
            official_title="삼성전자 에어컨 공식 제품군",
            official_url="https://www.samsung.com/sec/air-conditioners/all-air-conditioners/",
            supplies=["청소기 브러시", "부드러운 천", "고무장갑"],
            cautions=[
                "전원을 끄고 플러그 또는 차단기를 확인한 뒤 필터를 분리하세요.",
                "열교환기나 전기 부품에 물을 직접 뿌리지 마세요.",
            ],
            steps=[
                "전원을 끄고 제품이 완전히 멈춘 것을 확인해요.",
                "설명서에 따라 흡입 필터를 분리해 먼지를 제거해요.",
                "물세척 가능한 필터만 세척하고 그늘에서 완전히 말려요.",
                "냄새, 누수 또는 이상 소음이 있으면 전문 서비스를 요청해요.",
            ],
            keywords=["에어컨", "스탠드", "무풍", "무풍클래식", "비스포크 AI", "Bespoke AI", "air conditioner", "삼성"],
            specs=[
                "시리즈: Bespoke AI 무풍클래식",
                "제품 유형: 스탠드 에어컨",
                "정확한 모델명은 측면 또는 하단 라벨에서 확인",
            ],
        ),
        _product(
            id="samsung-ms23c3535ak",
            name="삼성 전자레인지",
            category="전자레인지",
            model="MS23C3535AK",
            method="삼성 전자레인지 대표 모델",
            summary="내부 음식물 흔적과 회전판을 닦고 충분히 건조해 냄새를 줄여요.",
            frequency="오염은 사용 후 · 내부 전체는 주 1회",
            days=7,
            minutes=10,
            official_title="MS23C3535AK 공식 지원",
            official_url="https://www.samsung.com/sec/support/model/MS23C3535AK/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "전원 플러그를 분리하고 내부가 식은 뒤 관리하세요.",
                "통풍구와 전기 부품에 물이 들어가지 않게 하세요.",
            ],
            steps=[
                "전원을 분리하고 내부가 식었는지 확인해요.",
                "회전판과 받침을 분리해 중성세제로 닦아요.",
                "내부 벽면과 문 안쪽의 음식물 흔적을 부드러운 천으로 닦아요.",
                "모든 부품을 완전히 말린 뒤 다시 장착해요.",
            ],
            keywords=["전자레인지", "microwave", "MS23C3535AK", "삼성"],
            specs=["모델명: MS23C3535AK", "제품 유형: 전자레인지"],
        ),
        _product(
            id="samsung-vacuum-family",
            name="삼성 무선청소기",
            category="청소기",
            method="삼성 Bespoke Jet 무선청소기 대표 제품군",
            summary="먼지통, 브러시와 세척 가능한 필터를 제품 설명서에 맞게 관리해요.",
            frequency="먼지통은 사용 후 · 브러시와 필터는 한 달마다",
            days=30,
            minutes=15,
            official_title="삼성전자 청소기 공식 제품군",
            official_url="https://www.samsung.com/sec/vacuum-cleaners/all-vacuum-cleaners/",
            supplies=["마른 천", "작은 솔", "가위"],
            cautions=[
                "배터리와 모터부는 물로 세척하지 마세요.",
                "세척한 필터는 완전히 건조한 뒤 장착하세요.",
            ],
            steps=[
                "전원을 끄고 먼지통을 비워요.",
                "브러시에 감긴 머리카락과 실을 제거해요.",
                "설명서에서 물세척 가능하다고 표시된 부품만 세척해요.",
                "부품을 완전히 건조한 뒤 정확히 조립해요.",
            ],
            keywords=["청소기", "무선청소기", "비스포크 제트", "vacuum", "삼성"],
        ),
        _product(
            id="samsung-dryer-family",
            name="삼성 건조기",
            category="건조기",
            method="삼성 Bespoke AI 건조기 대표 제품군",
            summary="보풀 필터는 사용할 때마다 비우고 센서와 열교환기는 설명서에 맞게 관리해요.",
            frequency="보풀 필터는 사용할 때마다 · 센서는 한 달마다",
            days=7,
            minutes=10,
            official_title="삼성전자 세탁기·건조기 공식 제품군",
            official_url="https://www.samsung.com/sec/washers-and-dryers/all-washers-and-dryers/",
            supplies=["부드러운 솔", "마른 천", "청소기 브러시"],
            cautions=[
                "젖은 필터를 장착하거나 열교환기 핀을 강하게 누르지 마세요.",
                "제품 내부를 임의로 분해하지 마세요.",
            ],
            steps=[
                "사용 후 보풀 필터를 꺼내 먼지를 제거해요.",
                "필터를 세척했다면 완전히 건조해 다시 장착해요.",
                "습도 센서를 부드러운 마른 천으로 닦아요.",
                "열교환기 관리는 모델별 설명서의 주기와 방법을 확인해요.",
            ],
            keywords=["건조기", "의류건조기", "dryer", "비스포크", "삼성"],
        ),
        _product(
            id="samsung-air-purifier-family",
            name="삼성 공기청정기",
            category="공기청정기",
            method="삼성 Bespoke 큐브 공기청정기 대표 제품군",
            summary="흡입구와 프리필터의 먼지를 제거하고 교체 필터 상태를 확인해요.",
            frequency="외부와 프리필터는 한 달마다",
            days=30,
            minutes=15,
            official_title="삼성전자 공기청정기 공식 제품군",
            official_url="https://www.samsung.com/sec/air-cleaner/all-air-cleaner/",
            supplies=["청소기 브러시", "마른 천"],
            cautions=[
                "집진·탈취 필터의 물세척 가능 여부를 설명서에서 확인하세요.",
                "전원을 분리한 뒤 필터 커버를 여세요.",
            ],
            steps=[
                "전원을 끄고 플러그를 분리해요.",
                "외부 흡입구의 먼지를 청소기 브러시로 제거해요.",
                "프리필터를 분리해 먼지를 털거나 허용된 경우 세척해요.",
                "필터를 완전히 건조하고 교체 필터의 상태를 확인해요.",
            ],
            keywords=["공기청정기", "공청기", "큐브", "air purifier", "삼성"],
        ),
        _product(
            id="samsung-dishwasher-family",
            name="삼성 식기세척기",
            category="식기세척기",
            method="삼성 Bespoke 식기세척기 대표 제품군",
            summary="필터, 배수구 주변과 분사 노즐의 음식물 찌꺼기를 관리해요.",
            frequency="필터는 주 1회 확인 · 내부 전체는 한 달마다",
            days=7,
            minutes=15,
            official_title="삼성전자 식기세척기 공식 제품군",
            official_url="https://www.samsung.com/sec/dishwashers/all-dishwashers/",
            supplies=["부드러운 솔", "마른 천", "고무장갑"],
            cautions=[
                "필터와 분사 노즐을 분리하기 전에 전원을 끄세요.",
                "배수 펌프와 내부 배관은 임의로 분해하지 마세요.",
            ],
            steps=[
                "전원을 끄고 내부가 식은 것을 확인해요.",
                "하단 필터를 설명서 순서에 따라 분리해 음식물 찌꺼기를 제거해요.",
                "분사 노즐 구멍과 문 패킹의 오염을 부드러운 솔로 닦아요.",
                "부품을 정확히 조립하고 빈 상태에서 허용된 관리 코스를 실행해요.",
            ],
            keywords=["식기세척기", "dishwasher", "비스포크", "삼성"],
        ),
        _product(
            id="samsung-kimchi-refrigerator-family",
            name="삼성 김치냉장고",
            category="김치냉장고",
            method="삼성 Bespoke 김치플러스 대표 제품군",
            summary="김치통, 선반과 문 고무패킹의 음식물 흔적과 물기를 관리해요.",
            frequency="오염은 발견 즉시 · 내부 전체는 한 달마다",
            days=30,
            minutes=20,
            official_title="삼성전자 김치냉장고 공식 제품군",
            official_url="https://www.samsung.com/sec/kimchi-refrigerators/all-kimchi-refrigerators/",
            supplies=["부드러운 천", "중성세제", "마른 수건"],
            cautions=[
                "김치통과 선반의 세척 가능 온도와 방법을 설명서에서 확인하세요.",
                "성에를 날카로운 도구나 열로 제거하지 마세요.",
            ],
            steps=[
                "보관 식품을 다른 냉장 공간으로 옮겨요.",
                "김치통과 분리 가능한 선반을 중성세제로 닦아요.",
                "내부 벽면과 문 고무패킹의 국물 흔적을 부드러운 천으로 닦아요.",
                "물기를 완전히 제거하고 설정 온도를 확인한 뒤 식품을 넣어요.",
            ],
            keywords=["김치냉장고", "김치플러스", "kimchi refrigerator", "삼성"],
        ),
        *_verified_samsung_washers(),
    ]


def _verified_samsung_washers() -> list[dict[str, Any]]:
    models = [
        (
            "samsung-wf25cb8895bw",
            "Bespoke AI 세탁기 25kg (올인원컨트롤)",
            "WF25CB8895BW",
            2023,
            "드럼 · 25kg · 올인원컨트롤",
            "https://images.samsung.com/kdp/goods/2023/01/16/77817fed-97aa-4f52-a0eb-3f11e19775d2.png?$450_N_PNG$",
            "https://www.samsung.com/sec/support/model/WF25CB8895BW/",
            "https://downloadcenter.samsung.com/content/UM/202603/20260330081210316/OID63540_IB_WF8000CK-AD_BEST_SimpleUX_WF25CB8895_KO_260206.pdf",
            ["25kg", "자동 세제함", "오토 오픈 도어"],
            ["세탁 용량: 25kg", "크기: 686 × 984 × 875mm", "무게: 104kg", "출시 연도: 2023년"],
        ),
        (
            "samsung-wf25dg8650bw",
            "AI 세탁기 25kg",
            "WF25DG8650BW",
            2025,
            "드럼 · 25kg · 심플컨트롤",
            "https://images.samsung.com/kdp/goods/2024/12/03/44ba347c-8feb-46de-b163-ee2926d98ef2.png?$450_N_PNG$",
            "https://www.samsung.com/sec/support/model/WF25DG8650BW/",
            "https://downloadcenter.samsung.com/content/UM/202603/20260330082143525/OID83489_IB_WF8000D-MD_SimpleUX_KO_260206.pdf",
            ["25kg", "심플컨트롤", "무세제통세척+"],
            ["세탁 용량: 25kg", "크기: 686 × 984 × 875mm", "무게: 98kg", "출시 연도: 2025년"],
        ),
        (
            "samsung-wf25dg8250bw",
            "AI 세탁기 25kg",
            "WF25DG8250BW",
            2025,
            "드럼 · 25kg",
            "https://images.samsung.com/kdp/goods/2025/01/03/7f1a3ccc-3e4b-435e-b98e-2dccc0fda7ef.png?$450_N_PNG$",
            "https://www.samsung.com/sec/support/model/WF25DG8250BW/",
            "https://downloadcenter.samsung.com/content/UM/202603/20260330082650980/OID83684_IB_WF8000D-MD_KO_260206.pdf",
            ["25kg", "무세제통세척+", "화이트"],
            ["세탁 용량: 25kg", "색상: 화이트", "출시 연도: 2025년"],
        ),
    ]
    return [_verified_samsung_washer(*model) for model in models]


def _verified_samsung_washer(
    id: str,
    name: str,
    model: str,
    year: int,
    method: str,
    image: str,
    support: str,
    manual: str,
    features: list[str],
    specs: list[str],
) -> dict[str, Any]:
    product_source = f"{id}-product"
    manual_source = f"{id}-manual"
    steps = [
        "전원 플러그를 빼고 세탁조 안에 세탁물이 없는지 확인해요.",
        "세제함을 설명서 순서대로 분리해 굳은 세제와 섬유유연제를 제거하고 완전히 말려 다시 끼워요.",
        "도어 유리와 고무 패킹의 주름 사이에서 이물질을 제거한 뒤 부드러운 천으로 닦고 도어를 열어 말려요.",
        "잔수 제거 호스로 물을 먼저 뺀 뒤 배수필터의 이물질을 제거하고 누수되지 않도록 정확히 다시 끼워요.",
        "세탁조를 비운 상태에서 무세제통세척 코스를 실행하고 세제나 세탁물을 넣지 않아요.",
    ]
    return {
        "id": id, "name": name, "type": "appliance", "categoryName": "세탁기",
        "brand": "삼성전자", "manufacturer": "삼성전자", "modelName": model,
        "seriesName": "삼성 드럼세탁기 25kg",
        "summary": "세제함, 도어와 고무 패킹, 배수필터, 세탁조를 모델 설명서에 맞춰 관리해요.",
        "frequency": "오염은 발견 즉시 · 세제함은 매주 확인 · 통세척 알림 시 실행",
        "recurrenceDays": 0, "estimatedMinutes": 25, "productMethod": method,
        "guideStatus": "정확한 모델과 공식 사용설명서를 확인했어요.",
        "guideBasis": f"삼성전자 공식 지원 페이지와 {model} 사용자 매뉴얼을 2026년 6월 13일 교차 확인했어요.",
        "guideSourceType": "official", "matchLevelLabel": "공식 설명서 확인 모델",
        "sourceTitle": f"{name} 공식 지원 페이지", "sourceUrl": support,
        "sourceCheckedAt": "2026-06-13",
        "sources": [
            {"id": product_source, "title": f"{name} 공식 지원 페이지", "url": support,
             "type": "officialProduct", "publisher": "삼성전자", "checkedAt": "2026-06-13",
             "supports": ["제품명", "모델명", "용량", "크기", "무게", "출시 연도", "대표 이미지"],
             "isOfficial": True, "isActive": True},
            {"id": manual_source, "title": f"{model} 사용자 매뉴얼", "url": manual,
             "type": "officialManual", "publisher": "삼성전자", "checkedAt": "2026-06-13",
             "supports": ["세제함 청소", "도어와 고무 패킹 관리", "배수필터 관리", "무세제통세척", "청소 안전사항"],
             "isOfficial": True, "isActive": True},
        ],
        "specSourceIds": {spec.split(":", 1)[0].strip(): [product_source] for spec in specs},
        "stepSourceIds": {str(index): [manual_source] for index in range(len(steps))},
        "reviewHistory": [{"status": "verified", "reviewer": "catalog-editor",
                           "reviewedAt": "2026-06-13",
                           "note": "공식 지원 페이지와 해당 모델 사용자 매뉴얼의 자가 관리 범위를 확인함."}],
        "productSpecs": specs,
        "supplies": ["부드러운 천", "마른 수건", "작은 부드러운 솔", "낮은 물받이"],
        "recommendedSupplies": ["부드러운 극세사 천", "작은 부드러운 솔", "낮은 물받이와 수건"],
        "recommendedProducts": [],
        "cautions": ["청소 전에는 전원 플러그를 빼세요.", "제품에 물을 직접 뿌리지 마세요.",
                     "배수필터를 열기 전 세탁수가 식었는지 확인하고 잔수를 먼저 제거하세요.",
                     "금속 수세미나 거친 도구를 사용하지 마세요.", "부품과 본체를 임의로 분리하지 마세요."],
        "steps": steps, "keywords": [model, "삼성 세탁기", "드럼세탁기", "25kg", "무세제통세척"],
        "reviewStatus": "verified", "reviewedBy": "catalog-editor",
        "reviewNote": "공식 지원 페이지와 해당 모델 사용자 매뉴얼 확인.",
        "officialManualUrl": manual, "supportUrl": support, "servicePhone": "1588-3366",
        "releaseYear": year, "isDiscontinued": False, "imageUrl": image,
        "modelFeatures": features, "consumables": [], "consumableDetails": [],
        "installationType": "프론트 로드 드럼세탁기",
    }


def _product(
    *,
    id: str,
    name: str,
    category: str,
    method: str,
    summary: str,
    frequency: str,
    days: int,
    minutes: int,
    official_title: str,
    official_url: str,
    supplies: list[str],
    cautions: list[str],
    steps: list[str],
    keywords: list[str],
    brand: str = "삼성전자",
    series: str = "",
    model: str = "",
    specs: list[str] | None = None,
    release_year: int | None = None,
) -> dict[str, Any]:
    official_id = f"{id}-official"
    guide_id = f"{id}-editorial-guide"
    product_specs = specs or ["정확한 모델명은 제품 라벨에서 확인"]
    spec_source_ids = {
        spec.split(":", maxsplit=1)[0]: [official_id]
        for spec in product_specs
        if ":" in spec
    }
    return {
        "id": id,
        "name": name,
        "type": "appliance",
        "categoryName": category,
        "brand": brand,
        "manufacturer": brand,
        "modelName": model,
        "seriesName": series,
        "summary": summary,
        "frequency": frequency,
        "recurrenceDays": days,
        "estimatedMinutes": minutes,
        "productMethod": method,
        "guideStatus": (
            "공식 지원 페이지에서 모델을 확인했어요. 관리 순서는 안전한 제품군 공통 범위로 안내해요."
            if model
            else (
                f"{brand} 공식 시리즈를 확인했어요. 정확한 모델별 분해·세척 방법은 제품 라벨과 설명서를 우선해요."
                if series
                else f"{brand} 공식 제품군을 확인했어요. 정확한 시리즈와 모델은 제품 라벨과 설명서를 우선해요."
            )
        ),
        "guideBasis": "공식 페이지는 제품 식별 근거로, 관리 순서는 앱 편집팀의 제품군 가이드로 분리해 표시해요.",
        "guideSourceType": "official" if model else "general",
        "matchLevelLabel": (
            "모델명 일치"
            if model
            else ("시리즈 기준" if series else "브랜드 제품군 기준")
        ),
        "sourceTitle": official_title,
        "sourceUrl": official_url,
        "sourceCheckedAt": CHECKED_AT,
        "sources": [
            {
                "id": official_id,
                "title": official_title,
                "url": official_url,
                "type": "officialSupport" if model else "officialProduct",
                "publisher": brand,
                "checkedAt": CHECKED_AT,
                "supports": ["모델명", "제품군"] if model else ["브랜드", "제품군"],
                "isOfficial": True,
                "isActive": True,
            },
            {
                "id": guide_id,
                "title": f"{category} 안전 관리 가이드",
                "url": None,
                "type": "generalGuidance",
                "publisher": "앱 편집팀",
                "checkedAt": CHECKED_AT,
                "supports": ["준비물", "안전 주의사항", "외부 관리 순서", "권장 확인 주기"],
                "isOfficial": False,
                "isActive": True,
            },
        ],
        "specSourceIds": spec_source_ids,
        "stepSourceIds": {
            str(index): [guide_id] for index, _ in enumerate(steps)
        },
        "reviewHistory": [
            {
                "status": "reviewed",
                "reviewer": "catalog-editor",
                "reviewedAt": CHECKED_AT,
                "note": "공식 제품 식별 정보와 일반 관리 가이드의 근거 범위를 분리해 검수함.",
            }
        ],
        "productSpecs": product_specs,
        "supplies": supplies,
        "recommendedSupplies": supplies,
        "recommendedProducts": [],
        "cautions": cautions,
        "steps": steps,
        "guideVideoUrl": None,
        "guideVideoTitle": None,
        "guideVideoChannel": None,
        "keywords": keywords,
        "reviewStatus": "reviewed",
        "reviewedBy": "catalog-editor",
        "reviewNote": "공식 식별 근거와 앱 편집 관리 가이드의 범위를 분리해 검수.",
        "officialManualUrl": None,
        "supportUrl": official_url,
        "servicePhone": "1588-3366",
        "releaseYear": release_year,
        "isDiscontinued": False,
        "imageUrl": None,
        "consumables": [],
        "installationType": None,
    }
